{% set name = "astroplan" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df4db93467e7f842952b4afeb1d584e89a0a70e99ec4e0aeed389747a7c069ae

build:
  noarch: python
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >3
    - setuptools
    - astropy >=1.3
  run:
    - python >3
    - numpy >=1.6
    - astropy >=1.3
    - pytz
    - matplotlib-base

test:
  imports:
    - astroplan
    - astroplan.plots

about:
  home: https://github.com/astropy/astroplan
  license: BSD 3-clause
  license_file:
    - LICENSE.rst

  license_family: BSD
  summary: Observation planning package for astronomers
  description: |
    astroplan is an observation planning package for astronomers that can help
    you plan for everything but the clouds. It is an in-development Astropy
    affiliated package that seeks to make your life as an observational
    astronomer a little less infuriating.
  doc_url: https://astroplan.readthedocs.io/
  dev_url: https://github.com/astropy/astroplan

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - bmorris3
