{% set name = "astroplan" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d98c5ea58f6131de391aa66c78e0b4d77649359b29dbc8fdee9385e0408c2f4b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools_scm
    - pip
  run:
    - python >=3.7
    - numpy
    - astropy >=4
    - pytz
    - six
    - matplotlib-base

test:
  imports:
    - astroplan
    - astroplan.plots

about:
  home: https://github.com/astropy/astroplan
  license: BSD-3-Clause
  license_file:
    - LICENSE.rst

  license_family: BSD
  summary: Observation planning package for astronomers
  description: |
    astroplan is an observation planning package for astronomers that can help
    you plan for everything but the clouds. It is an in-development Astropy
    affiliated package that seeks to make your life as an observational
    astronomer a little less infuriating.
  doc_url: https://astroplan.readthedocs.io/
  dev_url: https://github.com/astropy/astroplan

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - bmorris3
